services:
  http-balancer:
    build: .
    container_name: http-balancer
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal

  database:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./migrations/202505071000_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d balancer'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

  endpoint-first:
    image: nginxdemos/hello:plain-text
    networks:
      - internal
  endpoint-second:
    image: nginxdemos/hello:plain-text
    networks:
      - internal
  endpoint-third:
    image: nginxdemos/hello:plain-text
    networks:
      - internal

networks:
  internal:
    driver: bridge
